import PDFDocument from "pdfkit";
import { storagePut } from "./storage";

interface ChapterData {
  chapterNumber: number;
  title: string;
  content: string;
}

interface GeneratePdfOptions {
  ebookId: number;
  title: string;
  subject: string;
  language: string;
  tone: string;
  chapters: ChapterData[];
  hasWatermark: boolean;
  watermarkText?: string;
}

export async function generateEbookPdf(options: GeneratePdfOptions): Promise<{ key: string; url: string }> {
  const { ebookId, title, subject, language, tone, chapters, hasWatermark, watermarkText = "Generated by EbookAI Studio" } = options;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 72, bottom: 72, left: 72, right: 72 },
      info: {
        Title: title,
        Subject: subject,
        Creator: "EbookAI Studio",
        Producer: "EbookAI Studio",
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("error", reject);
    doc.on("end", async () => {
      try {
        const pdfBuffer = Buffer.concat(chunks);
        const fileKey = `ebooks/${ebookId}/ebook-${ebookId}.pdf`;
        const { key, url } = await storagePut(fileKey, pdfBuffer, "application/pdf");
        resolve({ key, url });
      } catch (err) {
        reject(err);
      }
    });

    // ─── Cover Page ───────────────────────────────────────────────────────────
    // Background rectangle
    doc.rect(0, 0, doc.page.width, doc.page.height).fill("#1a1a2e");

    // Decorative gradient bar
    doc.rect(0, 0, doc.page.width, 8).fill("#7c3aed");

    // Title
    doc.fillColor("#ffffff")
      .font("Helvetica-Bold")
      .fontSize(36)
      .text(title, 72, 200, { align: "center", width: doc.page.width - 144 });

    // Subject
    doc.fillColor("#a78bfa")
      .font("Helvetica")
      .fontSize(16)
      .text(subject, 72, 280, { align: "center", width: doc.page.width - 144 });

    // Metadata
    const toneLabels: Record<string, string> = {
      professional: "Professionnel",
      casual: "Décontracté",
      academic: "Académique",
      creative: "Créatif",
      motivational: "Motivant",
    };

    doc.fillColor("#6b7280")
      .font("Helvetica")
      .fontSize(12)
      .text(`Langue : ${language}  •  Ton : ${toneLabels[tone] || tone}`, 72, 340, {
        align: "center",
        width: doc.page.width - 144,
      });

    // Chapters count
    doc.fillColor("#4b5563")
      .fontSize(11)
      .text(`${chapters.length} chapitre${chapters.length > 1 ? "s" : ""}`, 72, 370, {
        align: "center",
        width: doc.page.width - 144,
      });

    // Bottom branding
    doc.fillColor("#374151")
      .fontSize(10)
      .text("EbookAI Studio", 72, doc.page.height - 100, {
        align: "center",
        width: doc.page.width - 144,
      });

    // Watermark on cover
    if (hasWatermark) {
      doc.save();
      doc.fillColor("#ffffff").opacity(0.08).fontSize(48).font("Helvetica-Bold");
      doc.rotate(-45, { origin: [doc.page.width / 2, doc.page.height / 2] });
      doc.text(watermarkText, 0, doc.page.height / 2 - 24, { align: "center", width: doc.page.width });
      doc.restore();
    }

    // ─── Table of Contents ────────────────────────────────────────────────────
    doc.addPage();
    doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0f0f1a");
    doc.rect(0, 0, doc.page.width, 8).fill("#7c3aed");

    doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(24)
      .text("Table des matières", 72, 60, { align: "left" });

    doc.moveTo(72, 100).lineTo(doc.page.width - 72, 100).strokeColor("#7c3aed").lineWidth(1).stroke();

    let tocY = 120;
    chapters.forEach((ch) => {
      if (tocY > doc.page.height - 100) {
        doc.addPage();
        doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0f0f1a");
        tocY = 60;
      }
      doc.fillColor("#a78bfa").font("Helvetica-Bold").fontSize(11)
        .text(`${ch.chapterNumber}.`, 72, tocY, { width: 30, continued: false });
      doc.fillColor("#e5e7eb").font("Helvetica").fontSize(11)
        .text(ch.title, 110, tocY, { width: doc.page.width - 200 });
      tocY += 28;
    });

    // ─── Chapters ─────────────────────────────────────────────────────────────
    chapters.forEach((ch) => {
      doc.addPage();
      doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0f0f1a");
      doc.rect(0, 0, doc.page.width, 8).fill("#7c3aed");

      // Chapter number badge
      doc.fillColor("#7c3aed").font("Helvetica-Bold").fontSize(12)
        .text(`CHAPITRE ${ch.chapterNumber}`, 72, 40, { align: "left" });

      // Chapter title
      doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(22)
        .text(ch.title, 72, 65, { width: doc.page.width - 144 });

      // Separator
      doc.moveTo(72, 105).lineTo(doc.page.width - 72, 105).strokeColor("#7c3aed").lineWidth(0.5).stroke();

      // Content — split into paragraphs
      const paragraphs = ch.content.split(/\n\n+/).filter(Boolean);
      let y = 120;

      for (const para of paragraphs) {
        const cleanPara = para.replace(/\n/g, " ").trim();
        if (!cleanPara) continue;

        // Check if it's a heading (starts with # or ##)
        if (cleanPara.startsWith("## ")) {
          const headingText = cleanPara.replace(/^## /, "");
          if (y + 30 > doc.page.height - 80) {
            doc.addPage();
            doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0f0f1a");
            y = 60;
          }
          doc.fillColor("#a78bfa").font("Helvetica-Bold").fontSize(14)
            .text(headingText, 72, y, { width: doc.page.width - 144 });
          y += doc.heightOfString(headingText, { width: doc.page.width - 144 }) + 12;
        } else if (cleanPara.startsWith("# ")) {
          const headingText = cleanPara.replace(/^# /, "");
          if (y + 30 > doc.page.height - 80) {
            doc.addPage();
            doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0f0f1a");
            y = 60;
          }
          doc.fillColor("#c4b5fd").font("Helvetica-Bold").fontSize(16)
            .text(headingText, 72, y, { width: doc.page.width - 144 });
          y += doc.heightOfString(headingText, { width: doc.page.width - 144 }) + 14;
        } else {
          const textHeight = doc.heightOfString(cleanPara, { width: doc.page.width - 144 });
          if (y + textHeight > doc.page.height - 80) {
            doc.addPage();
            doc.rect(0, 0, doc.page.width, doc.page.height).fill("#0f0f1a");
            y = 60;
          }
          doc.fillColor("#d1d5db").font("Helvetica").fontSize(11)
            .text(cleanPara, 72, y, { width: doc.page.width - 144, lineGap: 4 });
          y += textHeight + 14;
        }
      }

      // Watermark on each page
      if (hasWatermark) {
        doc.save();
        doc.fillColor("#ffffff").opacity(0.04).fontSize(36).font("Helvetica-Bold");
        doc.rotate(-45, { origin: [doc.page.width / 2, doc.page.height / 2] });
        doc.text(watermarkText, 0, doc.page.height / 2 - 18, { align: "center", width: doc.page.width });
        doc.restore();
      }
    });

    doc.end();
  });
}
